package jogo;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * @author Miguel Brito
 * @date 2018-06-03
 * @location Coimbra, Portugal
 */
public class teste extends javax.swing.JFrame {

    /**
     * Creates new form teste
     */
    public teste() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        caixa2 = new javax.swing.JComboBox();
        butao1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        butao2 = new javax.swing.JButton();
        butao3 = new javax.swing.JButton();
        caixa1 = new javax.swing.JComboBox();
        caixa3 = new javax.swing.JComboBox();

        button1.setLabel("button1");

        button2.setLabel("button2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocationByPlatform(true);

        caixa2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "200", "2000", "20000" }));
        caixa2.setEnabled(false);

        butao1.setText("butao 1");
        butao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butao1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("O João queria jogar um jogo, mas para jogar tinha de passar  num teste:\n\n\tprimeiro clica no botão1 depois escolhe a opção certa, para saberes se está certo clica no smile  :)");
        jScrollPane1.setViewportView(jTextArea1);

        butao2.setText("butao 2");
        butao2.setEnabled(false);
        butao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butao2ActionPerformed(evt);
            }
        });

        butao3.setText("butao 3");
        butao3.setEnabled(false);
        butao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butao3ActionPerformed(evt);
            }
        });

        caixa1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10 000", "100 000", "1 000 000" }));

        caixa3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "25", "125", "250" }));
        caixa3.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(butao2)
                        .addGap(18, 18, 18)
                        .addComponent(caixa2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(butao1)
                        .addGap(18, 18, 18)
                        .addComponent(caixa1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(butao3)
                        .addGap(18, 18, 18)
                        .addComponent(caixa3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butao1)
                    .addComponent(caixa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butao2)
                    .addComponent(caixa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butao3)
                    .addComponent(caixa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void butao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butao1ActionPerformed
        System.out.println("quanto é 1 000 x 1 000");
        
        
        if(caixa1.getSelectedItem().equals("1 000 000")){
                System.out.println("Muito bem");
               
                butao2.setEnabled(true);
                caixa2.setEnabled(true);
                /// desliga as caixas anteriores
                butao1.setEnabled(false);
                caixa1.setEnabled(false);
                System.out.println("Quanto é 4 x 4 x 1000?");
        }
        
        if(caixa1.getSelectedItem().equals("10 000")){
                System.out.println("Tenta de novo");
        }
        
        if(caixa1.getSelectedItem().equals("100 000")){
                System.out.println("Tenta de novo");
        }
        
    }//GEN-LAST:event_butao1ActionPerformed

    private void butao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butao2ActionPerformed
        
        if(caixa2.getSelectedItem().equals("20000")){
                System.out.println("Muito bem");
                System.out.println("Quanto é 5 x 5 x 10?");
                butao3.setEnabled(true);
                caixa3.setEnabled(true);
                /// desliga as caixas anteriores
                butao2.setEnabled(false);
                caixa2.setEnabled(false);
        }
        
        if(caixa2.getSelectedItem().equals("200")){
                System.out.println("Tenta de novo");
        }
        
        if(caixa2.getSelectedItem().equals("2000")){
                System.out.println("Tenta de novo");
        }
        
        
    }//GEN-LAST:event_butao2ActionPerformed

    private void butao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butao3ActionPerformed
       
         if(caixa3.getSelectedItem().equals("250")){
                System.out.println("Parabéns, acabaste o jogo!");
                //butao2.setEnabled(true);
                //caixa3.setEnabled(true);
                /// desliga as caixas anteriores
                butao3.setEnabled(false);
                caixa3.setEnabled(false);
                System.exit(0);
        }
        
        if(caixa3.getSelectedItem().equals("25")){
                System.out.println("Tenta de novo");
        }
        
        if(caixa3.getSelectedItem().equals("125")){
                System.out.println("Tenta de novo");
        }
        
        
    }//GEN-LAST:event_butao3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butao1;
    private javax.swing.JButton butao2;
    private javax.swing.JButton butao3;
    private java.awt.Button button1;
    private java.awt.Button button2;
    private javax.swing.JComboBox caixa1;
    private javax.swing.JComboBox caixa2;
    private javax.swing.JComboBox caixa3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
